# add start of loot table
with open("output.txt", "a") as file:
    file.write("""{
  "pools": [
    {
      "rolls": 1,
      "entries": [\n""")


#define read line funcion
def read_line ():
    f = open("input.txt", "r")

    line = f.readline()




#define "sceleton" of loot table
def item_loot(item_inn):


    # credits https://betterstack.com/community/questions/how-to-append-to-a-file-in-python/
    # credits https://www.geeksforgeeks.org/how-to-delete-data-from-file-in-python/
    
    # Open the file in append 
    with open("output.txt", "a") as file:
        file.write('        {' + "\n")
        file.write('          "type": "minecraft:item",' + "\n")
        #add item
        file.write('          "name": "' + item_inn + '",' + '\n')  # BUG 
        file.write('          "weight": 1' + "\n")
        file.write('        },' + "\n")


# set items for loop
items = int(input ("how many items in input.txt: "))

# set line variable
with open("input.txt", "r") as file:
    # loop reading and setting up items
    while items > 0 :
        items = items -1
        text = file.readline()
        
        #get rid of enter from line reading
        item_inn = text.replace("\n", "")

        
        
        item_loot(item_inn)




#add last part of loot table


# this part is mainly generated by ai

# Read the file
with open('output.txt', 'r',) as file:
    content = file.read()

# Remove the last character
updated_content = content[:-11]  

# Write the updated content back to the file
with open('output.txt', 'w',) as file:
    file.write(updated_content)

print("Last character removed successfully!")

with open("output.txt", "a") as file:
    file.write("""        }
      ]
    }
  ],
  "functions": []
}""")
